name: CI workflow

on:
  push:
    branches: [master, main, develop, saas-staging, saas-prod]
  pull_request:
    branches: [master, main, develop, saas-staging, saas-prod]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Install
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Install
        run: npm ci
      - name: Unit/Component testing
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run build
