name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:
  release:
    uses: TKaxv-7S/devops/.github/workflows/UIRelease.yml@main_tk
    with:
      version: ${{ inputs.version }}
    secrets: inherit
